classdef EECtrlRequest < robotics.ros.Message
    %EECtrlRequest MATLAB implementation of dobot_ros/EECtrlRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dobot_ros/EECtrlRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'fe884203ba35388b9947128186e4b842' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        ServoAngle
        Pump
        GripperAngle
    end
    
    properties (Constant, Hidden)
        PropertyList = {'GripperAngle', 'Pump', 'ServoAngle'} % List of non-constant message properties
        ROSPropertyList = {'gripper_angle', 'pump', 'servo_angle'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = EECtrlRequest(msg)
            %EECtrlRequest Construct the message object EECtrlRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function servoangle = get.ServoAngle(obj)
            %get.ServoAngle Get the value for property ServoAngle
            servoangle = double(obj.JavaMessage.getServoAngle);
        end
        
        function set.ServoAngle(obj, servoangle)
            %set.ServoAngle Set the value for property ServoAngle
            validateattributes(servoangle, {'numeric'}, {'nonempty', 'scalar'}, 'EECtrlRequest', 'ServoAngle');
            
            obj.JavaMessage.setServoAngle(servoangle);
        end
        
        function pump = get.Pump(obj)
            %get.Pump Get the value for property Pump
            pump = logical(obj.JavaMessage.getPump);
        end
        
        function set.Pump(obj, pump)
            %set.Pump Set the value for property Pump
            validateattributes(pump, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'EECtrlRequest', 'Pump');
            
            obj.JavaMessage.setPump(pump);
        end
        
        function gripperangle = get.GripperAngle(obj)
            %get.GripperAngle Get the value for property GripperAngle
            gripperangle = double(obj.JavaMessage.getGripperAngle);
        end
        
        function set.GripperAngle(obj, gripperangle)
            %set.GripperAngle Set the value for property GripperAngle
            validateattributes(gripperangle, {'numeric'}, {'nonempty', 'scalar'}, 'EECtrlRequest', 'GripperAngle');
            
            obj.JavaMessage.setGripperAngle(gripperangle);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ServoAngle = obj.ServoAngle;
            cpObj.Pump = obj.Pump;
            cpObj.GripperAngle = obj.GripperAngle;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ServoAngle = strObj.ServoAngle;
            obj.Pump = strObj.Pump;
            obj.GripperAngle = strObj.GripperAngle;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ServoAngle = obj.ServoAngle;
            strObj.Pump = obj.Pump;
            strObj.GripperAngle = obj.GripperAngle;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dobot_ros.EECtrlRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dobot_ros.EECtrlRequest;
            obj.reload(strObj);
        end
    end
end
